// <auto-generated />
using System;
using Amazon_eCommerce_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amazon_eCommerce_API.Migrations
{
    [DbContext(typeof(StoreContext))]
    partial class StoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Carts.Customer.CustomerCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerUserId");

                    b.ToTable("CustomerCarts");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Carts.Customer.CustomerCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CustomerCartItems");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Orders.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Preferences.Customer.CustomerPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerUserId")
                        .HasColumnType("int");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReceivePromotions")
                        .HasColumnType("bit");

                    b.Property<bool>("SubscribeToNewsletter")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerUserId")
                        .IsUnique();

                    b.ToTable("CustomerPreferences");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Products.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductBrandId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SellerUserId")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductBrandId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("SellerUserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Products.ProductBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProductBrands");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Products.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Products.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerifiedPurchase")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Products.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Products.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Shipments.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShippedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddressSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Subscriptions.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerUserId")
                        .IsUnique();

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Subscriptions.UserSubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserSubscriptionPlans");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Business.BusinessPaymentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusinessUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoutingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUserId", "AccountNumber")
                        .IsUnique()
                        .HasFilter("[AccountNumber] IS NOT NULL");

                    b.ToTable("BusinessPaymentProfiles");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Business.BusinessProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReceiveUpdates")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUserId")
                        .IsUnique();

                    b.ToTable("BusinessProfiles");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Business.BusinessStoreInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusinessUserId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuiteUnitFloor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUserId")
                        .IsUnique();

                    b.ToTable("BusinessStoreInformation");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Business.BusinessUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BusinessPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBusinessEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBusinessPhoneVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEmail")
                        .IsUnique()
                        .HasFilter("[BusinessEmail] IS NOT NULL");

                    b.ToTable("BusinessUsers");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Customer.CustomerPaymentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Last4Digits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentToken")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerUserId");

                    b.HasIndex("CustomerUserId", "PaymentToken")
                        .IsUnique()
                        .HasFilter("[PaymentToken] IS NOT NULL");

                    b.ToTable("CustomerPaymentProfiles");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Customer.CustomerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerUserId")
                        .HasColumnType("int");

                    b.Property<string>("DefaultShippingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerUserId")
                        .IsUnique();

                    b.ToTable("CustomerProfiles");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Customer.CustomerUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique()
                        .HasFilter("[EmailAddress] IS NOT NULL");

                    b.ToTable("CustomerUsers");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerBusinessInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyRegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SellerUserId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SellerUserId");

                    b.ToTable("SellerBusinessInformation");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerBusinessProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AgreedToTerms")
                        .HasColumnType("bit");

                    b.Property<int>("BusinessType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SellerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TermsAcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SellerUserId")
                        .IsUnique();

                    b.ToTable("SellerBusinessProfiles");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerPaymentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingAddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardBrand")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CardHolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpirationMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpirationYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefaultPaymentMethod")
                        .HasColumnType("bit");

                    b.Property<string>("Last4Digits")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaymentProviderToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SellerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SellerUserId", "Last4Digits", "CardBrand")
                        .IsUnique()
                        .HasFilter("[Last4Digits] IS NOT NULL AND [CardBrand] IS NOT NULL");

                    b.ToTable("SellerPaymentProfiles");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerPayoutAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountHolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Last4Digits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoutingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SellerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SellerUserId");

                    b.ToTable("SellerPayoutAccounts");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerPrimaryContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConfirmedActingOnBehalfOfBusiness")
                        .HasColumnType("bit");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryOfCitizenship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryOfIssue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentityDocumentType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IdentityProofExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityProofNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBusinessOwner")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLegalRepresentative")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SellerUserId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SellerUserId")
                        .IsUnique();

                    b.ToTable("SellerPrimaryContacts");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerStoreInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandOwnership")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasDiversityCertifications")
                        .HasColumnType("bit");

                    b.Property<bool>("HasUPCsForAllProducts")
                        .HasColumnType("bit");

                    b.Property<int>("SellerUserId")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrademarkStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SellerUserId")
                        .IsUnique();

                    b.ToTable("SellerStoreInformation");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("BusinessEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BusinessPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneNumberVerified")
                        .HasColumnType("bit");

                    b.Property<int>("OnboardingStep")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEmail")
                        .IsUnique()
                        .HasFilter("[BusinessEmail] IS NOT NULL");

                    b.ToTable("SellerUsers");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentBackUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentFrontUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProofOfAddress")
                        .HasColumnType("int");

                    b.Property<string>("ProofOfAddressDocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScheduledDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SellerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VerificationMethod")
                        .HasColumnType("int");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SellerUserId")
                        .IsUnique();

                    b.ToTable("SellerVerificationStatus");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerVerificationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IssuanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SellerUserId")
                        .HasColumnType("int");

                    b.Property<int?>("SellerVerificationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SellerUserId");

                    b.HasIndex("SellerVerificationId");

                    b.ToTable("SellerVerificationDocuments");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerVerificationOverview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BusinessAddressPostcardVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinalApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IdentityDocsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("PayoutMethodCleared")
                        .HasColumnType("bit");

                    b.Property<int>("SellerUserId")
                        .HasColumnType("int");

                    b.Property<bool>("TaxInterviewValidated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VideoMeetingCompleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SellerVerificationOverviews");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerW9", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressCountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BusinessFederalTaxClassification")
                        .HasColumnType("int");

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExemptPayeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FATCAExemptionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasForeignPartnersOrOwners")
                        .HasColumnType("bit");

                    b.Property<bool>("IsElectronicallySigned")
                        .HasColumnType("bit");

                    b.Property<int?>("LLCFederalTaxCode")
                        .HasColumnType("int");

                    b.Property<string>("LegalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequesterNameAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SellerUserId")
                        .HasColumnType("int");

                    b.Property<string>("SignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaxpayerIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaxpayerIdentificationType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SellerUserId")
                        .IsUnique();

                    b.ToTable("SellerW9");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.TaxProfile.SellerTaxProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusinessFederalTaxClassification")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DBAName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsUSPerson")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUSResidentEntity")
                        .HasColumnType("bit");

                    b.Property<int?>("LLCType")
                        .HasColumnType("int");

                    b.Property<int>("SellerUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaxClassification")
                        .HasColumnType("int");

                    b.Property<string>("TaxCountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxpayerIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaxpayerIdentificationType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SellerUserId")
                        .IsUnique();

                    b.ToTable("SellerTaxProfiles");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.TaxProfile.TaxAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AddressType")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SellerTaxProfileId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SellerTaxProfileId");

                    b.ToTable("TaxAddresses");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Carts.Customer.CustomerCart", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Customer.CustomerUser", "CustomerUser")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Carts.Customer.CustomerCartItem", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Carts.Customer.CustomerCart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Orders.OrderItem", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Preferences.Customer.CustomerPreferences", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Customer.CustomerUser", "CustomerUser")
                        .WithOne("CustomerPreferences")
                        .HasForeignKey("Amazon_eCommerce_API.Models.DBEntities.Preferences.Customer.CustomerPreferences", "CustomerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Products.Product", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Products.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Products.ProductBrand", "ProductBrand")
                        .WithMany("Products")
                        .HasForeignKey("ProductBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Products.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerUser", "SellerUser")
                        .WithMany()
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ProductBrand");

                    b.Navigation("ProductType");

                    b.Navigation("SellerUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Products.ProductImage", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Products.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Products.ProductReview", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Customer.CustomerUser", "CustomerUser")
                        .WithMany()
                        .HasForeignKey("CustomerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Products.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Products.ProductVariant", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Products.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Shipments.Shipment", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Orders.Order", "Order")
                        .WithMany("Shipments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Subscriptions.UserSubscription", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Customer.CustomerUser", "CustomerUser")
                        .WithOne("Subscription")
                        .HasForeignKey("Amazon_eCommerce_API.Models.DBEntities.Subscriptions.UserSubscription", "CustomerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Subscriptions.UserSubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerUser");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Business.BusinessPaymentProfile", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Business.BusinessUser", "BusinessUser")
                        .WithMany("BusinessPaymentProfiles")
                        .HasForeignKey("BusinessUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Business.BusinessProfile", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Business.BusinessUser", "BusinessUser")
                        .WithOne("BusinessProfile")
                        .HasForeignKey("Amazon_eCommerce_API.Models.DBEntities.Users.Business.BusinessProfile", "BusinessUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Business.BusinessStoreInformation", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Business.BusinessUser", "BusinessUser")
                        .WithOne("BusinessStoreInformation")
                        .HasForeignKey("Amazon_eCommerce_API.Models.DBEntities.Users.Business.BusinessStoreInformation", "BusinessUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BusinessUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Customer.CustomerPaymentProfile", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Customer.CustomerUser", "CustomerUser")
                        .WithMany("PaymentProfiles")
                        .HasForeignKey("CustomerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Customer.CustomerProfile", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Customer.CustomerUser", "CustomerUser")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("Amazon_eCommerce_API.Models.DBEntities.Users.Customer.CustomerProfile", "CustomerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerBusinessInformation", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerUser", "SellerUser")
                        .WithMany()
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerBusinessProfile", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerUser", "SellerUser")
                        .WithOne("SellerBusinessProfile")
                        .HasForeignKey("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerBusinessProfile", "SellerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerPaymentProfile", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerUser", "SellerUser")
                        .WithMany("SellerPaymentProfiles")
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerPayoutAccount", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerUser", "SellerUser")
                        .WithMany("SellerPayoutAccounts")
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerPrimaryContact", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerUser", "SellerUser")
                        .WithOne("SellerPrimaryContact")
                        .HasForeignKey("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerPrimaryContact", "SellerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerStoreInformation", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerUser", "SellerUser")
                        .WithOne("SellerStoreInformation")
                        .HasForeignKey("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerStoreInformation", "SellerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerVerification", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerUser", "SellerUser")
                        .WithOne("SellerVerificationStatus")
                        .HasForeignKey("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerVerification", "SellerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerVerificationDocument", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerUser", "SellerUser")
                        .WithMany("VerificationDocuments")
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerVerification", "SellerVerification")
                        .WithMany("Documents")
                        .HasForeignKey("SellerVerificationId");

                    b.Navigation("SellerUser");

                    b.Navigation("SellerVerification");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerW9", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerUser", "SellerUser")
                        .WithOne("SellerW9")
                        .HasForeignKey("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerW9", "SellerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.TaxProfile.SellerTaxProfile", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerUser", "SellerUser")
                        .WithOne("SellerTaxProfile")
                        .HasForeignKey("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.TaxProfile.SellerTaxProfile", "SellerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerUser");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.TaxProfile.TaxAddress", b =>
                {
                    b.HasOne("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.TaxProfile.SellerTaxProfile", "SellerTaxProfile")
                        .WithMany("TaxAddresses")
                        .HasForeignKey("SellerTaxProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerTaxProfile");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Carts.Customer.CustomerCart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Products.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Products.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Products.ProductBrand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Products.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Business.BusinessUser", b =>
                {
                    b.Navigation("BusinessPaymentProfiles");

                    b.Navigation("BusinessProfile");

                    b.Navigation("BusinessStoreInformation");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Customer.CustomerUser", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("CustomerPreferences");

                    b.Navigation("CustomerProfile");

                    b.Navigation("PaymentProfiles");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerUser", b =>
                {
                    b.Navigation("SellerBusinessProfile");

                    b.Navigation("SellerPaymentProfiles");

                    b.Navigation("SellerPayoutAccounts");

                    b.Navigation("SellerPrimaryContact");

                    b.Navigation("SellerStoreInformation");

                    b.Navigation("SellerTaxProfile");

                    b.Navigation("SellerVerificationStatus");

                    b.Navigation("SellerW9");

                    b.Navigation("VerificationDocuments");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.SellerVerification", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Amazon_eCommerce_API.Models.DBEntities.Users.Seller.TaxProfile.SellerTaxProfile", b =>
                {
                    b.Navigation("TaxAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
